sudo: false
language: node_js
node_js:
  - "10"

before_script:
  - npm install -g nyc mocha coveralls

install:
  - cd package/vemsy
  - npm install
  - npm run-script build

after_script:
  - npm run-script test
